# config.yaml

# Manitou Directories
# graphDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/copangraphs"
# linksDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/link_dicts"
# walkDictsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/walk_dicts_oriented"
# walkListsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/walk_lists_vectorized"
# modelDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/models"
# embeddingsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/embeddings"
# edgeEmbeddingsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/edge_embeddings"
# plotsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/plots"
# clustersDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/cluster_dicts"
# distancesDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/pairwise_distances"
# distancesDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/pairwise_distances"
# degreeDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/node_degrees"
# distDegDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/distance_degree"

# temp dir in pmg local
tempDir: "/pmglocal/rc3710"
# storageDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis"

# output directories
graphDir: "workflow/out/copangraphs"
linksDir: "workflow/out/link_dicts"
walkDictsDir: "workflow/out/walk_dicts_oriented"
walkListsDir: "workflow/out/walk_lists_vectorized"
modelDir: "workflow/out/vectorization_model/models"
embeddingsDir: "workflow/out/vectorization_model/embeddings"
edgeEmbeddingsDir: "workflow/out/vectorization_model/edge_embeddings"
plotsDir: "workflow/out/plots"
clustersDir: "workflow/out/cluster_dicts"
distancesDir: "workflow/out/pairwise_distances"
distancesDir: "workflow/out/pairwise_distances"
degreeDir: "workflow/out/node_degrees"
distDegDir: "workflow/out/distance_degree"
taxonomyDir: "workflow/out/taxonomy"
validationDir: "workflow/out/validation"

# Graph ID
graph_id: ["sample_1_0_02"]
# "camisim_megahit_20_0.02"

# Walk params
# walk_lengths: [30, 80]  # list of walk lengths
# n_walks: [30, 50]      # list of number of walks to perform per node
# p: [0.1, 0.5, 1.0]             # list of p values
# q: [0.1, 0.5, 1.0]             # list of q values
# seed: 1

# Walk params
walk_lengths: [30]  # list of walk lengths
n_walks: [30]      # list of number of walks to perform per node
p: [1.0]             # list of p values
q: [1.0]             # list of q values
seed: 1

# # Embedding params
# dimensions: [20, 60, 120]
window: 5
min_count: 5
sg: 0

dimensions: [20, 60]

# # t-SNE params
# perplexities: [10, 30, 50, 100]  # list of perplexity values
# n_iters: [1000, 3000, 5000]     # list of n_iter values
# n_components: 2
# random_state: 32

# t-SNE params
perplexities: [50, 100]  # list of perplexity values
n_iters: [3000, 5000]     # list of n_iter values
n_components: 2
random_state: 32
alpha: 0.2
tax_level: "species"
