# config.yaml

# Directories
graphDir: "config/copangraphs"
linksDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/link_dicts"
walkDictsDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/walk_dicts_oriented"
walkListsDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/walk_lists_vectorized"
modelDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/vectorization_model/models"
embeddingsDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/vectorization_model/embeddings"
edgeEmbeddingsDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/vectorization_model/edge_embeddings"
plotsDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/plots"
clustersDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/cluster_dicts"
distancesDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/pairwise_distances"
distancesDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/pairwise_distances"
degreeDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/node_degrees"
distDegDir: "/manitou/pmg/users/rc3710/copantopologyanalysis/workflow/out/distance_degree"

# Graph ID
graph_id: ["copan_0"]

# Walk params
walk_lengths: [30, 80]  # list of walk lengths
n_walks: [10, 50]      # list of number of walks to perform per node
# p: [1.0, 0.5, 2.0, 0.1]             # list of p values
# q: [1.0, 0.5, 2.0, 0.1]             # list of q values
p: [1.0]             # list of p values
q: [1.0]             # list of q values
seed: 1

# Embedding params
dimensions: [20, 60, 100, 140]
window: 5
min_count: 5
sg: 0

# t-SNE params
perplexities: [10, 30, 50, 100]  # list of perplexity values
n_iters: [1000, 3000, 5000]     # list of n_iter values
n_components: 2
random_state: 32
