# config.yaml

# Directories
graphDir: "config/copangraphs"
linksDir: "workflow/out/link_dicts"
walkDictsDir: "workflow/out/walk_dicts_oriented"
walkListsDir: "workflow/out/walk_lists_vectorized"
modelDir: "workflow/out/vectorization_model/models"
embeddingsDir: "workflow/out/vectorization_model/embeddings"
edgeEmbeddingsDir: "workflow/out/vectorization_model/edge_embeddings"
plotsDir: "workflow/out/plots"
clustersDir: "workflow/out/cluster_dicts"

# Graph ID
graph_id: ["copan_0"]

# Walk params
walk_lengths: [30, 80]  # list of walk lengths
n_walks: [10, 50]      # list of number of walks to perform per node
p: [1.0, 0.5, 2.0]             # list of p values
q: [1.0, 0.5, 2.0]             # list of q values
seed: 1

# Embedding params
dimensions: 128
window: 5
min_count: 5
sg: 0

# t-SNE params
perplexities: [5, 10, 30, 50, 100]  # list of perplexity values
n_iters: [500, 1000, 3000, 5000]     # list of n_iter values
n_components: 2
random_state: 32
