# config.yaml

# Manitou Directories
graphDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/copangraphs"
linksDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/link_dicts"
walkDictsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/walk_dicts_oriented"
walkListsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/walk_lists_vectorized"
modelDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/models"
embeddingsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/embeddings"
edgeEmbeddingsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/edge_embeddings"
plotsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/plots"
clustersDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/cluster_dicts"
distancesDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/pairwise_distances"
distancesDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/pairwise_distances"
degreeDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/node_degrees"
distDegDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/distance_degree"

# temp dir in pmg local
tempDir: "/pmglocal/rc3710"
# storageDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis"

# output directories
# graphDir: "workflow/out/copangraphs"
# linksDir: "workflow/out/link_dicts"
# walkDictsDir: "workflow/out/walk_dicts_oriented"
# walkListsDir: "workflow/out/walk_lists_vectorized"
# modelDir: "workflow/out/vectorization_model/models"
# embeddingsDir: "workflow/out/vectorization_model/embeddings"
# edgeEmbeddingsDir: "workflow/out/vectorization_model/edge_embeddings"
# plotsDir: "workflow/out/plots"
# clustersDir: "workflow/out/cluster_dicts"
# distancesDir: "workflow/out/pairwise_distances"
# distancesDir: "workflow/out/pairwise_distances"
# degreeDir: "workflow/out/node_degrees"
# distDegDir: "workflow/out/distance_degree"

# Graph ID
graph_id: ["copan_0"]

# # Walk params
# walk_lengths: [30, 80]  # list of walk lengths
# n_walks: [10, 50]      # list of number of walks to perform per node
# # p: [1.0, 0.5, 2.0, 0.1]             # list of p values
# # q: [1.0, 0.5, 2.0, 0.1]             # list of q values
# p: [1.0]             # list of p values
# q: [1.0]             # list of q values
# seed: 1

# # Embedding params
# dimensions: [20, 60, 100, 140]
# window: 5
# min_count: 5
# sg: 0

# # t-SNE params
# perplexities: [10, 30, 50, 100]  # list of perplexity values
# n_iters: [1000, 3000, 5000]     # list of n_iter values
# n_components: 2
# random_state: 32

# Walk params
walk_lengths: [30]  # list of walk lengths
n_walks: [10]      # list of number of walks to perform per node
# p: [1.0, 0.5, 2.0, 0.1]             # list of p values
# q: [1.0, 0.5, 2.0, 0.1]             # list of q values
p: [1.0]             # list of p values
q: [1.0]             # list of q values
seed: 1

# Embedding params
dimensions: [20]
window: 5
min_count: 5
sg: 0

# t-SNE params
perplexities: [10]  # list of perplexity values
n_iters: [1000]     # list of n_iter values
n_components: 2
random_state: 32
