# config.yaml

# Directories
graphDir: "config/copangraphs"
linksDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/link_dicts"
walkDictsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/walk_dicts_oriented"
walkListsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/walk_lists_vectorized"
modelDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/models"
embeddingsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/embeddings"
edgeEmbeddingsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/vectorization_model/edge_embeddings"
plotsDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/plots"
clustersDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/cluster_dicts"
distancesDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/pairwise_distances"
distancesDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/pairwise_distances"
degreeDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/node_degrees"
distDegDir: "/manitou/pmg/users/rc3710/CopanTopologyAnalysis/workflow/out/distance_degree"

# Graph ID
graph_id: ["dummy"]

# Walk params
walk_lengths: [30]  # list of walk lengths
n_walks: [10]      # list of number of walks to perform per node
p: [1.0]             # list of p values
q: [1.0]             # list of q values
seed: 1

# Embedding params
dimensions: [20]
window: 5
min_count: 5
sg: 0

# t-SNE params
perplexities: [5]  # list of perplexity values
n_iters: [300]     # list of n_iter values
n_components: 2
random_state: 32
